// Auto-generated by CrashVault. Bitte nicht manuell editieren.
window.CRASHVAULT_MODULE = {
  "id": "test",
  "name": "test",
  "tiles": [
    {
      "id": "knvhac4eau25",
      "type": "spruch-list",
      "title": "Sprücheliste",
      "x": 945,
      "y": 534,
      "w": 440,
      "h": 620,
      "z": 2,
      "state": {
        "items": [
          {
            "id": "w6rpac5zayzu",
            "text": "sdsdsd"
          },
          {
            "id": "nz54re0nb086",
            "text": "sdsd"
          }
        ]
      }
    }
  ],
  "_meta": {
    "lastSaved": "2026-06-02T18:36:30.459Z"
  }
};
