// Auto-generated by CrashVault. Bitte nicht manuell editieren.
window.CRASHVAULT_REGISTRY = {
  "modules": [
    {
      "id": "bwl",
      "name": "BWL",
      "color": "#38bdf8",
      "createdAt": "2026-06-02T17:51:56.892Z"
    },
    {
      "id": "rechnernetze",
      "name": "Rechnernetze",
      "color": "#a78bfa",
      "createdAt": "2026-06-02T18:43:34.071Z"
    }
  ],
  "_meta": {
    "lastSaved": "2026-06-02T18:43:36.987Z"
  }
};
