// Auto-generated by CrashVault. Bitte nicht manuell editieren.
window.CRASHVAULT_ACCOUNTS = {
  "accounts": [
    {
      "id": "u_v07m7r5k1g",
      "username": "henry",
      "displayName": "Henry",
      "passwordHash": "$2a$12$UY1EPf4e7BdZwL0f9DDKN.KEvcrICFUSEDRaucyjZJZ86u1n32e.W",
      "role": "admin",
      "tokenVersion": 1,
      "createdAt": "2026-06-05T08:35:20.884Z"
    }
  ],
  "config": {
    "allowSignup": false
  },
  "_meta": {
    "lastSaved": "2026-06-05T08:35:21.231Z"
  }
};
