// Auto-generated by CrashVault. Bitte nicht manuell editieren.
window.CRASHVAULT_VAULT = {
  "id": "v_ke4qrf64cz08",
  "name": "Henrys Vault",
  "description": "",
  "invites": [],
  "_meta": {
    "lastSaved": "2026-06-16T16:41:23.386Z"
  }
};
