// Auto-generated by CrashVault. Bitte nicht manuell editieren.
window.CRASHVAULT_USER = {
  "features": {},
  "tileLayouts": {},
  "preferences": {},
  "github": null,
  "_meta": {
    "lastSaved": "2026-06-16T16:41:23.969Z"
  }
};
