#!/usr/bin/env node
/**
 * One-off migration: turns the BWL repo's klausur-data.js into a CrashVault
 * module (modules/bwl/data.js) with two tile instances — a topic-list with
 * every topic + cards, and a spruch-list with every Ludolph saying. Also
 * copies referenced attachments into modules/bwl/files/ and rewrites the
 * attachment paths to point at the new module-scoped location.
 *
 * Run from the CrashVault repo root:
 *   node scripts/migrate-bwl.js  <BWL_REPO_PATH>
 *
 * The BWL repo is only read; nothing is written there.
 */

"use strict";

const fs = require("fs");
const path = require("path");

const BWL = process.argv[2];
if (!BWL) {
  console.error("Usage: node scripts/migrate-bwl.js <BWL_REPO_PATH>");
  process.exit(1);
}

const CV_ROOT = path.resolve(__dirname, "..");
const MODULE_ID = "bwl";
const MODULE_NAME = "BWL Klausurvorbereitung";
const MODULE_DIR = path.join(CV_ROOT, "modules", MODULE_ID);
const FILES_DIR  = path.join(MODULE_DIR, "files");
fs.mkdirSync(FILES_DIR, { recursive: true });

// Parse klausur-data.js (it's "window.KLAUSUR_DATA = {...};")
const dataText = fs.readFileSync(path.join(BWL, "klausur-data.js"), "utf8");
const m = dataText.match(/window\.KLAUSUR_DATA\s*=\s*([\s\S]+?);\s*$/);
if (!m) { console.error("klausur-data.js: unexpected format"); process.exit(1); }
const data = JSON.parse(m[1]);

// Tile ids — fixed so re-runs of this script don't churn them.
const TOPIC_TILE_ID = "tile_bwl_topics";
const SPRUCH_TILE_ID = "tile_bwl_sprueche";

const newPathFor = (oldPath) => {
  // Old paths are e.g. "notes/SWOT-Analyse erklärt.m4a" or
  // "materialien/Blue Ocean.pdf". We flatten everything into a single
  // module-scoped files/ directory.
  return `modules/${MODULE_ID}/files/${path.basename(oldPath)}`;
};

const copiedPaths = new Set();
function copyAttachment(oldRelPath) {
  const src = path.join(BWL, oldRelPath);
  if (!fs.existsSync(src)) { console.warn(" missing:", oldRelPath); return false; }
  const dst = path.join(FILES_DIR, path.basename(oldRelPath));
  if (!copiedPaths.has(dst)) {
    fs.copyFileSync(src, dst);
    copiedPaths.add(dst);
    console.log(" copied:", path.basename(oldRelPath));
  }
  return true;
}

// Rewrite + copy each attachment.
for (const t of (data.topics || [])) {
  for (const a of (t.attachments || [])) {
    if (!a.path) continue;
    const ok = copyAttachment(a.path);
    if (ok) a.path = newPathFor(a.path);
  }
}

const tiles = [
  {
    id: TOPIC_TILE_ID,
    type: "topic-list",
    title: "Klausurrelevante Themen",
    x: 40, y: 40, w: 880, h: 760, z: 1,
    state: { topics: data.topics || [] }
  },
  {
    id: SPRUCH_TILE_ID,
    type: "spruch-list",
    title: "Ludolph Sprüche",
    x: 960, y: 40, w: 480, h: 760, z: 2,
    state: { items: data.ludolph || [] }
  }
];

const moduleState = {
  id: MODULE_ID,
  name: MODULE_NAME,
  tiles,
  _meta: { lastSaved: new Date().toISOString() }
};
const out = "// Auto-generated by CrashVault. Bitte nicht manuell editieren.\n"
          + "window.CRASHVAULT_MODULE = " + JSON.stringify(moduleState, null, 2) + ";\n";
fs.writeFileSync(path.join(MODULE_DIR, "data.js"), out);
console.log("→ wrote modules/" + MODULE_ID + "/data.js");
console.log("   " + (data.topics?.length || 0) + " topics, " + (data.ludolph?.length || 0) + " Sprüche, " + copiedPaths.size + " Dateien kopiert");

// And drop BWL into the registry. We do this here too so the user gets a
// ready-to-go state after one command. Registry is rewritten atomically.
const REG_FILE = path.join(CV_ROOT, "modules", "registry.js");
let registry = { modules: [] };
if (fs.existsSync(REG_FILE)) {
  const t = fs.readFileSync(REG_FILE, "utf8");
  const rm = t.match(/window\.CRASHVAULT_REGISTRY\s*=\s*([\s\S]+?);\s*$/);
  if (rm) registry = JSON.parse(rm[1]);
}
if (!Array.isArray(registry.modules)) registry.modules = [];
if (!registry.modules.some(x => x.id === MODULE_ID)) {
  registry.modules.unshift({
    id: MODULE_ID,
    name: MODULE_NAME,
    color: "#38bdf8",
    createdAt: new Date().toISOString()
  });
}
const regOut = "// Auto-generated by CrashVault. Bitte nicht manuell editieren.\n"
             + "window.CRASHVAULT_REGISTRY = " + JSON.stringify({ modules: registry.modules, _meta: { lastSaved: new Date().toISOString() } }, null, 2) + ";\n";
fs.writeFileSync(REG_FILE, regOut);
console.log("→ updated modules/registry.js");
