// GET  /api/data?vault=<vid>&module=<mid>  → { state, sha }
// POST /api/data?vault=<vid>&module=<mid>  body: { state, expectedSha, fileShas } → { sha }
//
// Per-module state under a vault. The file lives at
// vaults/<vid>/modules/<mid>/data.js. The `fileShas` paths must all live
// under vaults/<vid>/modules/<mid>/files/ — cross-vault writes are rejected.

const gh = require("./_github.js");
const auth = require("./_auth.js");

function parseDataFile(text) {
  const m = text.match(/window\.CRASHVAULT_MODULE\s*=\s*([\s\S]+?);\s*$/);
  if (!m) throw new Error("module data file format unexpected");
  return JSON.parse(m[1]);
}
function buildDataFile(state) {
  const dump = {
    id: state.id,
    name: state.name,
    tiles: state.tiles || [],
    _meta: { lastSaved: new Date().toISOString() }
  };
  return "// Auto-generated by CrashVault. Bitte nicht manuell editieren.\n"
       + "window.CRASHVAULT_MODULE = " + JSON.stringify(dump, null, 2) + ";\n";
}

module.exports = async (req, res) => {
  try {
    const url = new URL(req.url, `http://${req.headers.host || "x"}`);
    const vaultId = url.searchParams.get("vault");
    const moduleId = url.searchParams.get("module");
    if (!gh.validVaultId(vaultId))  return gh.sendJson(res, 400, { error: "vault query param invalid" });
    if (!gh.validModuleId(moduleId)) return gh.sendJson(res, 400, { error: "module query param invalid" });
    const ctx = await auth.requireVaultMember(req, vaultId);
    const dataPath = gh.vaultModuleDataPath(vaultId, moduleId);
    const filePrefix = gh.vaultModuleFilesPrefix(vaultId, moduleId);

    if (req.method === "GET") {
      const sha = await gh.getRefSha();
      const c = await gh.getContent(dataPath);
      let state;
      if (!c) state = null;
      else {
        const raw = c.content || (await gh.getBlob(c.sha)).content;
        state = parseDataFile(gh.b64ToUtf8(raw));
      }
      return gh.sendJson(res, 200, { state, sha });
    }

    if (req.method === "POST") {
      const body = await gh.readJson(req);
      const { state, expectedSha, fileShas = [] } = body;
      if (!state || !Array.isArray(state.tiles)) return gh.sendJson(res, 400, { error: "Invalid state payload" });

      const currentSha = await gh.getRefSha();
      if (expectedSha && currentSha !== expectedSha) {
        return gh.sendJson(res, 409, { error: "Repo wurde inzwischen geändert. Bitte ↻ Neu laden und nochmal speichern." });
      }
      const baseCommit = await gh.getCommit(currentSha);
      const dataBlob = await gh.createBlob(gh.utf8ToB64(buildDataFile(state)));
      const treeEntries = [{ path: dataPath, mode: "100644", type: "blob", sha: dataBlob.sha }];

      for (const f of fileShas) {
        if (!f || !f.path || !f.sha) continue;
        if (!f.path.startsWith(filePrefix)) {
          return gh.sendJson(res, 400, { error: `file path außerhalb des Moduls: ${f.path}` });
        }
        treeEntries.push({ path: f.path, mode: "100644", type: "blob", sha: f.sha });
      }

      const tree = await gh.createTree(baseCommit.tree.sha, treeEntries);
      const message = fileShas.length
        ? `[${ctx.user.username}] ${ctx.vault.name}/${moduleId}: data + ${fileShas.length} Anhang(e)`
        : `[${ctx.user.username}] ${ctx.vault.name}/${moduleId}: data aktualisiert`;
      await auth.loadUserContext(ctx.user);
      const author = (ctx.user.github && ctx.user.github.commitEmail)
        ? { name: ctx.user.github.login || ctx.user.username, email: ctx.user.github.commitEmail }
        : null;
      const commit = await gh.createCommit(message, tree.sha, currentSha, author);
      await gh.updateRef(commit.sha);
      return gh.sendJson(res, 200, { sha: commit.sha, changes: treeEntries.length });
    }

    res.setHeader("Allow", "GET, POST");
    return gh.sendJson(res, 405, { error: "Method not allowed" });
  } catch (e) {
    return gh.sendError(res, e);
  }
};
