// GET  /api/registry?vault=<vid>  → { registry, sha }
// POST /api/registry?vault=<vid>  body: { registry, expectedSha } → { sha }
//
// The per-vault module registry lives at vaults/<vid>/modules/registry.js.
// Membership in the vault is required for both directions.

const gh = require("./_github.js");
const auth = require("./_auth.js");

const DEFAULTS = { modules: [] };

function parseRegistry(text) {
  const m = text.match(/window\.CRASHVAULT_REGISTRY\s*=\s*([\s\S]+?);\s*$/);
  if (!m) throw new Error("registry.js format unexpected");
  return JSON.parse(m[1]);
}
function buildRegistry(state) {
  const dump = { modules: state.modules || [], _meta: { lastSaved: new Date().toISOString() } };
  return "// Auto-generated by CrashVault. Bitte nicht manuell editieren.\n"
       + "window.CRASHVAULT_REGISTRY = " + JSON.stringify(dump, null, 2) + ";\n";
}

module.exports = async (req, res) => {
  try {
    const url = new URL(req.url, `http://${req.headers.host || "x"}`);
    const vaultId = url.searchParams.get("vault");
    if (!gh.validVaultId(vaultId)) return gh.sendJson(res, 400, { error: "vault query param invalid" });
    const ctx = await auth.requireVaultMember(req, vaultId);
    const REGISTRY_FILE = gh.vaultModuleRegistryPath(vaultId);

    if (req.method === "GET") {
      const sha = await gh.getRefSha();
      const c = await gh.getContent(REGISTRY_FILE);
      let registry;
      if (!c) registry = DEFAULTS;
      else {
        const raw = c.content || (await gh.getBlob(c.sha)).content;
        registry = parseRegistry(gh.b64ToUtf8(raw));
      }
      return gh.sendJson(res, 200, { registry, sha });
    }

    if (req.method === "POST") {
      const body = await gh.readJson(req);
      const { registry, expectedSha } = body;
      if (!registry || !Array.isArray(registry.modules)) {
        return gh.sendJson(res, 400, { error: "Invalid registry payload" });
      }
      for (const m of registry.modules) {
        if (!gh.validModuleId(m.id)) return gh.sendJson(res, 400, { error: `Ungültige Modul-ID: ${m.id}` });
      }

      const currentSha = await gh.getRefSha();
      if (expectedSha && currentSha !== expectedSha) {
        return gh.sendJson(res, 409, { error: "Repo wurde inzwischen geändert. Bitte ↻ Neu laden und nochmal speichern." });
      }

      const baseCommit = await gh.getCommit(currentSha);
      const blob = await gh.createBlob(gh.utf8ToB64(buildRegistry(registry)));
      const tree = await gh.createTree(baseCommit.tree.sha, [
        { path: REGISTRY_FILE, mode: "100644", type: "blob", sha: blob.sha }
      ]);
      await auth.loadUserContext(ctx.user);
      const author = (ctx.user.github && ctx.user.github.commitEmail)
        ? { name: ctx.user.github.login || ctx.user.username, email: ctx.user.github.commitEmail }
        : null;
      const commit = await gh.createCommit(
        `[${ctx.user.username}] ${ctx.vault.name}: registry aktualisiert`,
        tree.sha, currentSha, author
      );
      await gh.updateRef(commit.sha);
      return gh.sendJson(res, 200, { sha: commit.sha });
    }

    res.setHeader("Allow", "GET, POST");
    return gh.sendJson(res, 405, { error: "Method not allowed" });
  } catch (e) {
    return gh.sendError(res, e);
  }
};
