// Auto-generated by CrashVault. Bitte nicht manuell editieren.
window.CRASHVAULT_VAULTS = {
  "vaults": [
    {
      "id": "v_ke4qrf64cz08",
      "name": "Henrys Vault",
      "color": "#38bdf8",
      "owner": "u_v07m7r5k1g",
      "members": [
        "u_v07m7r5k1g"
      ],
      "createdAt": "2026-06-16T16:41:23.000Z"
    }
  ],
  "_meta": {
    "lastSaved": "2026-06-16T16:41:23.000Z"
  }
};
